sample :drum_heavy_kick
sleep 2
sample :drum_tom_mid_soft
sleep 2
sample :drum_tom_mid_hard
sleep 2
sample :drum_tom_lo_soft
sleep 2
sample :drum_tom_lo_hard
sleep 2
sample :drum_tom_hi_soft
sleep 2
sample :drum_tom_hi_hard
sleep 2
sample :drum_splash_soft
sleep 2
sample :drum_splash_hard
sleep 2
sample :drum_snare_soft
sleep 2
sample :drum_snare_hard
sleep 2
sample :drum_cymbal_soft
sleep 2
sample :drum_cymbal_hard
sleep 2
sample :drum_cymbal_open
sleep 2
sample :drum_cymbal_closed
sleep 2
sample :drum_cymbal_pedal
sleep 2
sample :drum_bass_soft
sleep 2
sample :drum_bass_hard
sleep 2
sample :drum_cowbell
sleep 2
sample :drum_roll
sleep sample_duration(:drum_roll)


sample :sn_dub
sleep 2
sample :sn_dolf
sleep 2
sample :sn_zome
sleep 2
